apiVersion: v1
kind: Service
metadata:
  name: vprocache01  #this name should be same as the application.properties file
spec:
  ports:
    - port: 11211            # accept the request from port 11211
      targetPort: vpromc-port  # forward the request on port 11211
      protocol: TCP
  selector:
    app: vpromc
  type: ClusterIP
